-- Contacts (Stores synced GHL contacts with enhancements)
CREATE TABLE IF NOT EXISTS contacts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ghl_id VARCHAR(255) UNIQUE, -- GoHighLevel Contact ID
  email VARCHAR(255) NOT NULL,
  name TEXT,
  tags JSON DEFAULT '[]', -- Stores array of strings, e.g., ["priority_group_A", "high_intent"]
  custom_fields JSON, -- Store relevant GHL custom fields
  last_email_sequence INTEGER DEFAULT 0, -- Track sequence progress if needed
  joined_date TIMESTAMP,
  contact_source TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Unified Emails Table (Templates, Priority Emails, Experiments)
CREATE TABLE IF NOT EXISTS emails (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER, -- Link to a future users table if multi-tenant
  type TEXT CHECK(type IN ('template', 'priority', 'experiment')) NOT NULL,
  name TEXT, -- User-friendly name for the email/template/experiment
  subject TEXT,
  body_html TEXT,
  body_text TEXT, -- Plain text version
  key_angle TEXT, -- Concept from Draw.io
  version INTEGER DEFAULT 1,
  base_email_id INTEGER REFERENCES emails(id), -- For experiments based on a template
  start_date TIMESTAMP, -- For priority/scheduled emails
  end_date TIMESTAMP, -- For priority emails
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Experiment Variants (Generated by AI)
CREATE TABLE IF NOT EXISTS experiment_variants (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email_id INTEGER NOT NULL REFERENCES emails(id), -- Links to the parent 'experiment' email
  variant_letter TEXT, -- e.g., 'A', 'B', 'C'
  subject TEXT,
  body_html TEXT,
  body_text TEXT,
  key_angle TEXT,
  ai_parameters JSON, -- Store info like model used, prompt, temperature
  -- Performance metrics can be added later or calculated dynamically
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Email Deliveries (Tracks individual sends and interactions)
CREATE TABLE IF NOT EXISTS email_deliveries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email_id INTEGER NOT NULL REFERENCES emails(id), -- Which email was sent
  variant_id INTEGER REFERENCES experiment_variants(id), -- Which specific variant, if applicable
  contact_id INTEGER NOT NULL REFERENCES contacts(id), -- Who received it
  ghl_message_id VARCHAR(255), -- Store GHL's ID for correlation if possible
  status TEXT CHECK(status IN ('queued', 'sent', 'delivered', 'opened', 'clicked', 'bounced', 'complained', 'unsubscribed', 'failed')) DEFAULT 'queued',
  sent_at TIMESTAMP,
  delivered_at TIMESTAMP,
  opened_at TIMESTAMP,
  clicked_at TIMESTAMP,
  bounced_at TIMESTAMP,
  complained_at TIMESTAMP,
  unsubscribed_at TIMESTAMP,
  error_message TEXT, -- Store reason for failure/bounce
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_email_deliveries_contact_email ON email_deliveries (contact_id, email_id);

-- User Settings (For AI Personalization)
CREATE TABLE IF NOT EXISTS user_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER UNIQUE, -- Link to a future users table
  avatar_name TEXT,
  avatar_bio TEXT,
  avatar_company_name TEXT,
  avatar_inspiration_name TEXT,
  avatar_role TEXT,
  avatar_website TEXT,
  email_signature_html TEXT,
  icp_fears TEXT,
  icp_pain_points TEXT,
  icp_insecurities TEXT,
  icp_transformations TEXT, -- Success stories
  icp_description TEXT, -- Ideal Customer Profile summary
  icp_key_objectives TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Error Logs
CREATE TABLE IF NOT EXISTS error_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  context TEXT, -- e.g., 'GHL Sync', 'Priority Send Job'
  error_message TEXT,
  stack_trace TEXT,
  payload JSON -- Relevant data at the time of error
);

-- Integration Connections (Store OAuth tokens, API keys, etc.)
CREATE TABLE IF NOT EXISTS integration_connections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  provider TEXT NOT NULL, -- 'ghl', 'openai', etc.
  access_token TEXT,
  refresh_token TEXT,
  token_expires_at TIMESTAMP,
  is_active BOOLEAN DEFAULT true,
  config JSON, -- Additional configuration data
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, provider) -- One connection per provider per user
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(email);
CREATE INDEX IF NOT EXISTS idx_contacts_ghl_id ON contacts(ghl_id);
CREATE INDEX IF NOT EXISTS idx_emails_type ON emails(type);
CREATE INDEX IF NOT EXISTS idx_emails_active ON emails(is_active);
CREATE INDEX IF NOT EXISTS idx_experiment_variants_email_id ON experiment_variants(email_id);
CREATE INDEX IF NOT EXISTS idx_email_deliveries_status ON email_deliveries(status);
CREATE INDEX IF NOT EXISTS idx_email_deliveries_ghl_message_id ON email_deliveries(ghl_message_id);
